VDS-3089: Update csvhelper and attempt to fix breaking changes
VirtoCommerce/vc-module-catalog-export-import pull request #13
Opened 2021-10-04 14:34 UTC by pushnitsa

Description: 

--

QA-test: 

Demo-test: 

Download artifact URL:

2021-10-04 15:43 UTC, trueboroda requested changes

2021-10-04 15:43 UTC, trueboroda commented on src/VirtoCommerce.DescriptionExportImportModule.Core/Models/ImportConfiguration.cs
> +    public static class ImportConfiguration
Rename to smth like this: CsvConfigurationFactory

2021-10-05 11:23 UTC, asvishnyakov requested changes

2021-10-05 11:23 UTC, asvishnyakov commented on src/VirtoCommerce.DescriptionExportImportModule.Core/Models/ImportConfiguration.cs
> +    public class ImportConfigurationFactory
Sealed, no virtual 'cause we don't allow extend module

2021-10-05 11:23 UTC, asvishnyakov commented on src/VirtoCommerce.DescriptionExportImportModule.Data/Services/CsvImportReporter.cs
> +                await _streamWriter.DisposeAsync();
Why Flush was removed?

2021-10-05 11:23 UTC, asvishnyakov commented on src/VirtoCommerce.DescriptionExportImportModule.Data/Services/CsvPagedDataImporter.cs
> +            SetupErrorHandlers(progressCallback, configuration, errorsContext, importProgress, importReporter);
Does it moved specially or just unintentionally?

2021-10-19 11:34 UTC, closed without merging