VDS-2923 Implement the physical products exporting
VirtoCommerce/vc-module-catalog-export-import pull request #17
Opened 2021-10-08 14:33 UTC by trueboroda

Description: 

--

QA-test: VDS-2926

Demo-test: VDS-2927

Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CatalogExportImport_1.0.0-pr-17-d8e28b93.zip

2021-10-08 14:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/VirtoCommerce/vc-module-catalog-export-import?pullRequest=17) <br/>All committers have signed the CLA.

2021-10-08 15:15 UTC, Pav-el commented on src/VirtoCommerce.CatalogExportImportModule.Core/Models/CsvPhysicalProduct.cs
> +            Lenght = product.Length;
LengTH?

2021-10-08 15:16 UTC, Pav-el commented on src/VirtoCommerce.CatalogExportImportModule.Core/ModuleConstants.cs
> +                {DataTypes.PhysicalProduct, "Physical product export"},
productS?

2021-10-08 15:28 UTC, Pav-el commented on src/VirtoCommerce.CatalogExportImportModule.Web/Scripts/dialogs/exportConfirm-dialog.tpl.html
> +<div class="modal-body" ng-switch on="dataType">
ng-switch seems not working here

2021-10-11 07:52 UTC, Pav-el approved these changes

2021-10-11 09:09 UTC, ilyawzrd requested changes

2021-10-11 09:09 UTC, ilyawzrd commented on src/VirtoCommerce.CatalogExportImportModule.Web/Scripts/module.js
> +            predefinedDataType: { key: 'Physical Products', value: 'PhysicalProduct' }
Why did you rename this value? It should stay 'CatalogProduct'

2021-10-11 10:05 UTC, ilyawzrd approved these changes

2021-10-12 10:34 UTC, merged