VDS-3182: Add validation for physical product import
VirtoCommerce/vc-module-catalog-export-import pull request #26
Opened 2021-10-21 08:15 UTC by asvishnyakov

Description: 

--

QA-test: VDS-2916

Demo-test: VDS-2917

Download artifact URL:

2021-10-21 09:21 UTC, trueboroda requested changes

2021-10-21 09:21 UTC, trueboroda commented on src/VirtoCommerce.CatalogExportImportModule.Data/Validation/ImportPhysicalProductValidator.cs
> +        private static readonly char[] ProductSkuIllegalCharacters = { '$', '+', ';', '=', '%', '{', '}', '[', ']', '|', '@', '~', '!', '^', '*', '&', '(', ')', '<', '>' };
it should be the const on a platform level.

2021-10-21 09:21 UTC, trueboroda commented on src/VirtoCommerce.CatalogExportImportModule.Data/Validation/ImportPhysicalProductValidator.cs
> +                .Must((record, packageType, context) =>
Use a not cascade mode for this rule.

2021-10-21 09:21 UTC, trueboroda commented on src/VirtoCommerce.CatalogExportImportModule.Data/Validation/ImportPhysicalProductValidator.cs
> +                .WithImportState()
Use not cascade mode for this rule

2021-10-21 09:23 UTC, trueboroda requested changes

2021-10-21 09:23 UTC, trueboroda commented on src/VirtoCommerce.CatalogExportImportModule.Data/Validation/ImportPhysicalProductValidator.cs
> +            RuleFor(record => record.Record.WeightUnit)
Use not cascade mode for this rule

2021-10-21 09:23 UTC, trueboroda commented on src/VirtoCommerce.CatalogExportImportModule.Data/Validation/ImportPhysicalProductValidator.cs
> +            RuleFor(record => record.Record.TaxType)
Use not cascade mode for this rule

2021-10-21 12:39 UTC, asvishnyakov commented on src/VirtoCommerce.CatalogExportImportModule.Data/Validation/ImportPhysicalProductValidator.cs
> +        private static readonly char[] ProductSkuIllegalCharacters = { '$', '+', ';', '=', '%', '{', '}', '[', ']', '|', '@', '~', '!', '^', '*', '&', '(', ')', '<', '>' };
https://virtocommerce.atlassian.net/browse/PT-5208 that's all what I can do at the moment :)

2021-10-22 10:52 UTC, asvishnyakov commented on src/VirtoCommerce.CatalogExportImportModule.Data/Validation/ImportPhysicalProductValidator.cs
> +                .Must((record, packageType, context) =>
Fixed

2021-10-22 10:52 UTC, asvishnyakov commented on src/VirtoCommerce.CatalogExportImportModule.Data/Validation/ImportPhysicalProductValidator.cs
> +                .WithImportState()
Fixed

2021-10-22 10:52 UTC, asvishnyakov commented on src/VirtoCommerce.CatalogExportImportModule.Data/Validation/ImportPhysicalProductValidator.cs
> +            RuleFor(record => record.Record.WeightUnit)
Fixed

2021-10-22 10:53 UTC, asvishnyakov commented on src/VirtoCommerce.CatalogExportImportModule.Data/Validation/ImportPhysicalProductValidator.cs
> +            RuleFor(record => record.Record.TaxType)
Fixed

2021-10-22 10:57 UTC, trueboroda approved these changes

2021-10-28 13:59 UTC, merged